import { BaseContent } from "../types";

export interface GuideContent extends BaseContent {
  iconName: string;
  href: string;
}

export const GUIDES_DATABASE: GuideContent[] = [
  {
    id: "switch-guide",
    name: "키보드 스위치 가이드",
    iconName: "Zap",
    href: "/kr/switches",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "복잡한 축 이름 뒤에 숨겨진 실제 타건감과 구매 팁을 확인하세요.",
    aiStrengthsKo: ["타건감 중심 설명", "구매 전 체크리스트"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "gaming-mouse-vs-normal",
    name: "게이밍 마우스 vs 일반 마우스",
    iconName: "Mouse",
    href: "/kr/guides/gaming-mouse-vs-normal-mouse",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "센서와 무게가 왜 중요한지, 내게 맞는 선택 기준을 제안합니다.",
    aiStrengthsKo: ["센서 정밀도 비교", "그립감과 무게의 관계"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "8k-polling-rate",
    name: "8K 폴링레이트, 필요한가요?",
    iconName: "Zap",
    href: "/kr/guides/8k-polling-rate",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "고주사율 유저라면 확인해보세요. 성능 향상과 주의사항을 정리했습니다.",
    aiStrengthsKo: ["주사율과의 시너지", "CPU 점유율 영향"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "dead-pixel-policy",
    name: "불량화소와 무결점 정책",
    iconName: "ShieldCheck",
    href: "/kr/guides/dead-pixel-policy",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "모니터 브랜드별 교환 기준과 체크리스트를 한눈에 비교합니다.",
    aiStrengthsKo: ["브랜드별 정책 비교", "무결점 보증의 실체"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "backlight-bleed-ips-glow",
    name: "빛샘 vs IPS Glow",
    iconName: "Moon",
    href: "/kr/guides/backlight-bleed-vs-ips-glow",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "패널 특성에 따른 정상 범위를 알고 불필요한 고민을 줄여보세요.",
    aiStrengthsKo: ["정상/불량 구분법", "패널별 특성 이해"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "full-aluminum-keyboard",
    name: "풀알루미늄 키보드 입문",
    iconName: "Keyboard",
    href: "/kr/guides/full-aluminum-keyboard",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "금속 하우징이 만드는 정갈한 소리와 선택 시 꼭 확인해야 할 점들.",
    aiStrengthsKo: ["하우징 소재의 차이", "가성비 알루미늄 추천"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
];
