import { SwitchContent } from "../types";

export const SWITCH_DATABASE: SwitchContent[] = [
  {
    id: "standard-linear",
    slug: "standard-linear",
    category: "switch",
    brand: "Generic",
    name: "일반 리니어축",
    switchType: "linear",
    soundLevel: "normal",
    actuationForceG: 45,
    bottomOutForceG: 60,
    travelMm: 4.0,
    bestFor: ["beginner", "gaming", "office"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "가장 대중적이고 호불호가 적은 방식입니다. 누를 때 걸리는 느낌 없이 끝까지 매끄럽게 내려갑니다.",
    aiBuyingCheckKo: ["키압이 너무 무겁지 않은지 확인", "윤활 여부에 따라 서걱임 차이가 큼"],
    aiCautionKo: "입력 지점이 명확하지 않아 처음에는 오타가 날 수 있습니다.",
  },
  {
    id: "standard-tactile",
    slug: "standard-tactile",
    category: "switch",
    brand: "Generic",
    name: "일반 택타일축",
    switchType: "tactile",
    soundLevel: "normal",
    actuationForceG: 50,
    bottomOutForceG: 65,
    travelMm: 4.0,
    bestFor: ["beginner", "typing"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "키를 누를 때 중간에 '톡' 하고 걸리는 느낌이 있어 내가 키를 눌렀다는 확신을 줍니다.",
    aiBuyingCheckKo: ["걸림의 강도가 본인에게 맞는지 확인", "소음이 리니어보다 약간 클 수 있음"],
    aiCautionKo: "장시간 타이핑 시 리니어보다 손가락 피로도가 약간 높을 수 있습니다.",
  },
  {
    id: "standard-clicky",
    slug: "standard-clicky",
    category: "switch",
    brand: "Generic",
    name: "일반 클릭축",
    switchType: "clicky",
    soundLevel: "loud",
    actuationForceG: 50,
    bottomOutForceG: 60,
    travelMm: 4.0,
    bestFor: ["beginner", "custom"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "기계식 키보드 하면 떠오르는 '찰칵' 소리가 나는 방식입니다. 확실한 피드백이 특징입니다.",
    aiBuyingCheckKo: ["주변 사람들에게 소음 피해를 주지 않는지 확인"],
    aiCautionKo: "소음이 매우 크기 때문에 공공장소나 사무실에서는 사용이 거의 불가능합니다.",
  },
  {
    id: "silent-linear",
    slug: "silent-linear",
    category: "switch",
    brand: "Generic",
    name: "저소음 리니어축",
    switchType: "linear",
    soundLevel: "quiet",
    actuationForceG: 45,
    bottomOutForceG: 60,
    travelMm: 3.7,
    bestFor: ["office", "silent"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "리니어의 구조에 댐퍼를 추가하여 소음을 획기적으로 줄인 방식입니다.",
    aiBuyingCheckKo: ["끝까지 눌렀을 때 느껴지는 '먹먹함'이 괜찮은지 확인"],
    aiCautionKo: "일반 축에 비해 타건감이 다소 답답하게 느껴질 수 있습니다.",
  },
  {
    id: "magnetic-he",
    slug: "magnetic-he",
    category: "switch",
    brand: "Generic",
    name: "자석축 (Hall Effect)",
    switchType: "magnetic",
    soundLevel: "normal",
    actuationForceG: 30,
    bottomOutForceG: 50,
    travelMm: 4.0,
    bestFor: ["gaming"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "자석의 원리를 이용해 입력 지점을 자유롭게 조절할 수 있는 최첨단 방식입니다. 래피드 트리거 기능의 핵심입니다.",
    aiBuyingCheckKo: ["전용 소프트웨어 지원 여부 확인", "래피드 트리거 기능 포함 여부"],
    aiCautionKo: "매우 민감하게 설정할 경우 스치기만 해도 입력될 수 있어 주의가 필요합니다.",
  },
  {
    id: "ice-cream-series",
    slug: "ice-cream-series",
    category: "switch",
    brand: "Kailh / Various",
    name: "아이스크림축 계열",
    switchType: "linear",
    soundLevel: "normal",
    actuationForceG: null,
    bottomOutForceG: null,
    travelMm: null,
    bestFor: ["custom", "beginner"],
    status: "published",
    updatedAt: "2024-05-13",
    aiBeginnerSummaryKo: "이름은 감성적이지만 실제로는 부드러운 리니어 계열로 분류되는 경우가 많습니다. 제품마다 키압과 소음이 다르므로 이름만 보고 판단하면 안 됩니다.",
    aiBuyingCheckKo: ["실제 제조사와 상세 스펙(리니어/택타일)을 반드시 확인", "하우징 소재가 POM인지 확인"],
    aiCautionKo: "감성적인 이름에 현혹되기보다 실제 스위치 방식이 리니어인지 택타일인지 확인하는 것이 중요합니다.",
    aiNamingWarningKo: "아이스크림, 말차, 피치 같은 이름은 체감 설명이 아니라 마케팅 이름인 경우가 많습니다. 실제 구매 전에는 리니어/택타일/클릭 여부와 키압, 소음 정보를 확인하는 편이 안전합니다.",
  },
];
