import { KeyboardContent } from "../../types";

export const KEYBOARD_DATABASE: KeyboardContent[] = [
  {
    id: "rainy75",
    slug: "rainy75",
    category: "keyboard",
    brand: "WOB Lab",
    name: "Rainy75",
    layout: "75%",
    switchType: ["linear"],
    isHotSwap: true,
    material: "aluminum",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "10만원대",
    features: ["가성비 종결", "풀 알루미늄", "무선 3모드"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "aluminum_preferred",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "세부 스펙은 판매처별 옵션과 생산 시기에 따라 확인이 필요합니다.",
    },
    specTags: ["75%", "Aluminum", "Wireless"],
    aiSummaryKo: "가성비 알루미늄 키보드 시장을 뒤흔든 베스트셀러 모델입니다. 뛰어난 타건음과 빌드 퀄리티를 자랑합니다.",
    aiStrengthsKo: ["압도적인 가성비", "순정 상태에서도 훌륭한 타건음", "세련된 디자인"],
    aiCautionsKo: ["품절이 잦아 구매가 어려울 수 있음", "전용 소프트웨어의 편의성이 다소 부족함"],
  },
  {
    id: "realforce-r3",
    slug: "realforce-r3",
    category: "keyboard",
    brand: "Topre",
    name: "Realforce R3",
    layout: "full",
    switchType: ["capacitive"],
    isHotSwap: false,
    material: "plastic",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "30만원대",
    features: ["무접점 방식", "독보적인 타건감", "APC 기능"],
    basicFilters: {
      layout: "full",
      connection: "wireless",
      feel: "quiet",
      noise: "quiet_preferred",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      actuationForceG: null,
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "APC, 키압, 연결 옵션 등은 모델 세부 옵션 확인이 필요합니다.",
    },
    specTags: ["Full Layout", "Topre", "Silent"],
    aiSummaryKo: "무접점 키보드의 끝판왕으로 불리는 리얼포스의 최신 모델입니다. 특유의 '초콜릿 부러뜨리는' 타건감이 특징입니다.",
    aiStrengthsKo: ["독보적인 무접점 타건감", "긴 내구성", "뛰어난 안정성"],
    aiCautionsKo: ["매우 높은 가격", "플라스틱 하우징에 대한 아쉬움"],
  }
];
