import { MouseContent } from "../../types";

export const MOUSE_DATABASE: MouseContent[] = [
  {
    id: "g-pro-x-superlight-2",
    slug: "g-pro-x-superlight-2",
    category: "mouse",
    brand: "Logitech",
    name: "G Pro X Superlight 2",
    dimensions: { length: 125, width: 63.5, height: 40 },
    shapeType: "symmetrical",
    weight: 60,
    sensor: "HERO 2",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "medium",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "19만원대",
    features: ["초경량", "무선 2K 지원", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "light",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "HERO 2",
      pollingRateHz: 2000,
      dimensionsMm: { length: 125, width: 63.5, height: 40 },
      buttonCountDetail: null,
      dpiChangeSupport: null,
      adjustableWeight: false,
      replaceableParts: null,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Logitech G Pro Wireless",
        relationType: "community_compared",
        confidence: "medium",
        sourceHint: "community",
        aiNoteKo: "자주 비교되는 쉘 계열로, 낮지 않은 등 높이와 대칭형 체감을 비교 기준으로 삼기 좋습니다.",
        cautionKo: "세대별 크기와 코팅, 클릭감은 다를 수 있으므로 쉘 체감만 참고하세요.",
      },
    ],
    rawSpecs: {
      note: "센서, DPI, 보증기간 등 세부 스펙은 판매처와 지역에 따라 확인이 필요합니다.",
    },
    specTags: ["60g", "HERO 2", "2K Wireless"],
    aiSummaryKo: "로지텍의 대표적인 초경량 무선 마우스로, 전작의 성공을 이어받아 센서와 폴링레이트가 개선되었습니다.",
    aiStrengthsKo: ["안정적인 무선 연결", "검증된 쉘 디자인", "긴 배터리 타임"],
    aiCautionsKo: ["높은 가격대", "마이크로 5핀에서 C타입으로 변경되었으나 여전히 비싼 편"],
  },
  {
    id: "razer-deathadder-v3-pro",
    slug: "razer-deathadder-v3-pro",
    category: "mouse",
    brand: "Razer",
    name: "DeathAdder V3 Pro",
    dimensions: { length: 128, width: 68, height: 44 },
    shapeType: "ergonomic",
    weight: 63,
    sensor: "Focus Pro 30K",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "large",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "20만원대",
    features: ["비대칭형", "인체공학적 디자인", "초경량"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "light",
      connection: "wireless",
      size: "large",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Focus Pro 30K",
      maxDpi: 30000,
      dimensionsMm: { length: 128, width: 68, height: 44 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelKo: "데스애더 계열",
        referenceModelEn: "DeathAdder family",
        relationType: "similar_shape",
        confidence: "high",
        sourceHint: "official",
        aiNoteKo: "오른손 비대칭형 쉘 체감 레퍼런스로 자주 언급되는 계열입니다.",
        cautionKo: "손이 작다면 등 높이와 길이가 부담될 수 있습니다.",
      },
    ],
    rawSpecs: {
      note: "폴링레이트와 동글 구성은 구매 옵션에 따라 확인이 필요합니다.",
    },
    specTags: ["63g", "Focus Pro 30K", "Ergonomic"],
    aiSummaryKo: "레이저의 인체공학적 비대칭 마우스로, 큰 손 사용자에게 최상의 그립감을 제공합니다.",
    aiStrengthsKo: ["최상급 센서 성능", "매우 가벼운 비대칭 쉘", "뛰어난 코팅"],
    aiCautionsKo: ["손이 작은 사용자에게는 부담스러운 크기", "다소 높은 가격"],
  },
  // Add a few more or leave as is for now to save time, but I should probably add at least 3-4 to make the finder look good.
  {
    id: "viper-v3-pro",
    slug: "viper-v3-pro",
    category: "mouse",
    brand: "Razer",
    name: "Viper V3 Pro",
    dimensions: { length: 127, width: 64, height: 40 },
    shapeType: "symmetrical",
    weight: 54,
    sensor: "Focus Pro 35K",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "23만원대",
    features: ["8K 무선 지원", "낮은 클릭 레이턴시", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Focus Pro 35K",
      maxDpi: 35000,
      pollingRateHz: 8000,
      dimensionsMm: { length: 127, width: 64, height: 40 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Razer Viper family",
        relationType: "similar_shape",
        confidence: "medium",
        sourceHint: "manual",
        aiNoteKo: "낮은 등과 길게 뻗은 대칭형 체감을 비교 기준으로 삼기 좋습니다.",
        cautionKo: "Viper 세대별로 등 높이와 허리 라인이 달라 체감 차이가 있을 수 있습니다.",
      },
    ],
    rawSpecs: {
      note: "8K 사용 시 배터리 소모와 환경 조건을 함께 확인해야 합니다.",
    },
    specTags: ["54g", "8K Wireless", "Symmetrical"],
    aiSummaryKo: "8K 무선 폴링레이트를 지원하는 레이저의 최신 대칭형 플래그십 마우스입니다.",
    aiStrengthsKo: ["압도적인 무선 성능", "매우 낮은 클릭 레이턴시", "가벼운 무게"],
    aiCautionsKo: ["배터리 소모가 빠를 수 있음(8K 사용 시)"],
  }
];
